### ISSUE TITLE
Time to retire?

### ISSUE THREAD

**Issue by pwtyler** [pantheon-systems/terminus-retry#4]
Retries were added to Terminus core in 3.5.0.

Can this project be retired, or are there any features missing that this addresses?

https://github.com/pantheon-systems/terminus/releases/tag/3.5.0
https://github.com/pantheon-systems/terminus/pull/2588

cc @ryanshoover

**Comment by ryanshoover** [comment]
Yeah that's a god call. I don't think anyone is actively using this plugin. I'll archive the repo
